SECTION = "//div[contains(@class, 'pv-top-card-v2-ctas')]"
MORE_ACTIONS = '//span[text()="More"]/parent::button'
CONNECT = '//span[text()="Connect"]/parent::div'
SEND_WITHOUT_NOTE = '//span[text()="Send"]/parent::button'
SHEET_URL = 'https://docs.google.com/spreadsheets/d/1UBpscD6ubxRR525lwcGZyie_NnoSDKy2aWL-WfepRb0/edit#gid=0'
PROFILE_NAME = 'Profile 9'
USER_DIR_PATH = 'C:/Users/User/AppData/Local/Google/Chrome/User Data'
LOGIN = 'ruben21294@gmail.com'
PASSWORD = '102030123Er'
INPUT_JSON = 'data/input/musicsearch.json'
DRIVER_DIR = 'driver/chromedriver.exe'